const data = [
 {
   "Name": "Wii Sports",
   "Platform": "Wii",
   "Year_of_Release": "2006",
   "Genre": "Sports",
   "Publisher": "Nintendo",
   "NA_Sales": 41.36,
   "EU_Sales": 28.96,
   "JP_Sales": 3.77,
   "Other_Sales": 8.45,
   "Global_Sales": 82.53,
   "Critic_Score": 76,
   "Critic_Count": 51,
   "User_Score": "8",
   "User_Count": 322,
   "Developer": "Nintendo",
   "Rating": "E"
 },
 {
   "Name": "Super Mario Bros.",
   "Platform": "NES",
   "Year_of_Release": "1985",
   "Genre": "Platform",
   "Publisher": "Nintendo",
   "NA_Sales": 29.08,
   "EU_Sales": 3.58,
   "JP_Sales": 6.81,
   "Other_Sales": 0.77,
   "Global_Sales": 40.24,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Mario Kart Wii",
   "Platform": "Wii",
   "Year_of_Release": "2008",
   "Genre": "Racing",
   "Publisher": "Nintendo",
   "NA_Sales": 15.68,
   "EU_Sales": 12.76,
   "JP_Sales": 3.79,
   "Other_Sales": 3.29,
   "Global_Sales": 35.52,
   "Critic_Score": 82,
   "Critic_Count": 73,
   "User_Score": "8.3",
   "User_Count": 709,
   "Developer": "Nintendo",
   "Rating": "E"
 },
 {
   "Name": "Wii Sports Resort",
   "Platform": "Wii",
   "Year_of_Release": "2009",
   "Genre": "Sports",
   "Publisher": "Nintendo",
   "NA_Sales": 15.61,
   "EU_Sales": 10.93,
   "JP_Sales": 3.28,
   "Other_Sales": 2.95,
   "Global_Sales": 32.77,
   "Critic_Score": 80,
   "Critic_Count": 73,
   "User_Score": "8",
   "User_Count": 192,
   "Developer": "Nintendo",
   "Rating": "E"
 },
 {
   "Name": "Pokemon Red/Pokemon Blue",
   "Platform": "GB",
   "Year_of_Release": "1996",
   "Genre": "Role-Playing",
   "Publisher": "Nintendo",
   "NA_Sales": 11.27,
   "EU_Sales": 8.89,
   "JP_Sales": 10.22,
   "Other_Sales": 1,
   "Global_Sales": 31.37,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Tetris",
   "Platform": "GB",
   "Year_of_Release": "1989",
   "Genre": "Puzzle",
   "Publisher": "Nintendo",
   "NA_Sales": 23.2,
   "EU_Sales": 2.26,
   "JP_Sales": 4.22,
   "Other_Sales": 0.58,
   "Global_Sales": 30.26,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "New Super Mario Bros.",
   "Platform": "DS",
   "Year_of_Release": "2006",
   "Genre": "Platform",
   "Publisher": "Nintendo",
   "NA_Sales": 11.28,
   "EU_Sales": 9.14,
   "JP_Sales": 6.5,
   "Other_Sales": 2.88,
   "Global_Sales": 29.8,
   "Critic_Score": 89,
   "Critic_Count": 65,
   "User_Score": "8.5",
   "User_Count": 431,
   "Developer": "Nintendo",
   "Rating": "E"
 },
 {
   "Name": "Wii Play",
   "Platform": "Wii",
   "Year_of_Release": "2006",
   "Genre": "Misc",
   "Publisher": "Nintendo",
   "NA_Sales": 13.96,
   "EU_Sales": 9.18,
   "JP_Sales": 2.93,
   "Other_Sales": 2.84,
   "Global_Sales": 28.92,
   "Critic_Score": 58,
   "Critic_Count": 41,
   "User_Score": "6.6",
   "User_Count": 129,
   "Developer": "Nintendo",
   "Rating": "E"
 },
 {
   "Name": "New Super Mario Bros. Wii",
   "Platform": "Wii",
   "Year_of_Release": "2009",
   "Genre": "Platform",
   "Publisher": "Nintendo",
   "NA_Sales": 14.44,
   "EU_Sales": 6.94,
   "JP_Sales": 4.7,
   "Other_Sales": 2.24,
   "Global_Sales": 28.32,
   "Critic_Score": 87,
   "Critic_Count": 80,
   "User_Score": "8.4",
   "User_Count": 594,
   "Developer": "Nintendo",
   "Rating": "E"
 },
 {
   "Name": "Duck Hunt",
   "Platform": "NES",
   "Year_of_Release": "1984",
   "Genre": "Shooter",
   "Publisher": "Nintendo",
   "NA_Sales": 26.93,
   "EU_Sales": 0.63,
   "JP_Sales": 0.28,
   "Other_Sales": 0.47,
   "Global_Sales": 28.31,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Nintendogs",
   "Platform": "DS",
   "Year_of_Release": "2005",
   "Genre": "Simulation",
   "Publisher": "Nintendo",
   "NA_Sales": 9.05,
   "EU_Sales": 10.95,
   "JP_Sales": 1.93,
   "Other_Sales": 2.74,
   "Global_Sales": 24.67,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Mario Kart DS",
   "Platform": "DS",
   "Year_of_Release": "2005",
   "Genre": "Racing",
   "Publisher": "Nintendo",
   "NA_Sales": 9.71,
   "EU_Sales": 7.47,
   "JP_Sales": 4.13,
   "Other_Sales": 1.9,
   "Global_Sales": 23.21,
   "Critic_Score": 91,
   "Critic_Count": 64,
   "User_Score": "8.6",
   "User_Count": 464,
   "Developer": "Nintendo",
   "Rating": "E"
 },
 {
   "Name": "Pokemon Gold/Pokemon Silver",
   "Platform": "GB",
   "Year_of_Release": "1999",
   "Genre": "Role-Playing",
   "Publisher": "Nintendo",
   "NA_Sales": 9,
   "EU_Sales": 6.18,
   "JP_Sales": 7.2,
   "Other_Sales": 0.71,
   "Global_Sales": 23.1,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Wii Fit",
   "Platform": "Wii",
   "Year_of_Release": "2007",
   "Genre": "Sports",
   "Publisher": "Nintendo",
   "NA_Sales": 8.92,
   "EU_Sales": 8.03,
   "JP_Sales": 3.6,
   "Other_Sales": 2.15,
   "Global_Sales": 22.7,
   "Critic_Score": 80,
   "Critic_Count": 63,
   "User_Score": "7.7",
   "User_Count": 146,
   "Developer": "Nintendo",
   "Rating": "E"
 },
 {
   "Name": "Kinect Adventures!",
   "Platform": "X360",
   "Year_of_Release": "2010",
   "Genre": "Misc",
   "Publisher": "Microsoft Game Studios",
   "NA_Sales": 15,
   "EU_Sales": 4.89,
   "JP_Sales": 0.24,
   "Other_Sales": 1.69,
   "Global_Sales": 21.81,
   "Critic_Score": 61,
   "Critic_Count": 45,
   "User_Score": "6.3",
   "User_Count": 106,
   "Developer": "Good Science Studio",
   "Rating": "E"
 },
 {
   "Name": "Wii Fit Plus",
   "Platform": "Wii",
   "Year_of_Release": "2009",
   "Genre": "Sports",
   "Publisher": "Nintendo",
   "NA_Sales": 9.01,
   "EU_Sales": 8.49,
   "JP_Sales": 2.53,
   "Other_Sales": 1.77,
   "Global_Sales": 21.79,
   "Critic_Score": 80,
   "Critic_Count": 33,
   "User_Score": "7.4",
   "User_Count": 52,
   "Developer": "Nintendo",
   "Rating": "E"
 },
 {
   "Name": "Grand Theft Auto V",
   "Platform": "PS3",
   "Year_of_Release": "2013",
   "Genre": "Action",
   "Publisher": "Take-Two Interactive",
   "NA_Sales": 7.02,
   "EU_Sales": 9.09,
   "JP_Sales": 0.98,
   "Other_Sales": 3.96,
   "Global_Sales": 21.04,
   "Critic_Score": 97,
   "Critic_Count": 50,
   "User_Score": "8.2",
   "User_Count": 3994,
   "Developer": "Rockstar North",
   "Rating": "M"
 },
 {
   "Name": "Grand Theft Auto: San Andreas",
   "Platform": "PS2",
   "Year_of_Release": "2004",
   "Genre": "Action",
   "Publisher": "Take-Two Interactive",
   "NA_Sales": 9.43,
   "EU_Sales": 0.4,
   "JP_Sales": 0.41,
   "Other_Sales": 10.57,
   "Global_Sales": 20.81,
   "Critic_Score": 95,
   "Critic_Count": 80,
   "User_Score": "9",
   "User_Count": 1588,
   "Developer": "Rockstar North",
   "Rating": "M"
 },
 {
   "Name": "Super Mario World",
   "Platform": "SNES",
   "Year_of_Release": "1990",
   "Genre": "Platform",
   "Publisher": "Nintendo",
   "NA_Sales": 12.78,
   "EU_Sales": 3.75,
   "JP_Sales": 3.54,
   "Other_Sales": 0.55,
   "Global_Sales": 20.61,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Brain Age: Train Your Brain in Minutes a Day",
   "Platform": "DS",
   "Year_of_Release": "2005",
   "Genre": "Misc",
   "Publisher": "Nintendo",
   "NA_Sales": 4.74,
   "EU_Sales": 9.2,
   "JP_Sales": 4.16,
   "Other_Sales": 2.04,
   "Global_Sales": 20.15,
   "Critic_Score": 77,
   "Critic_Count": 58,
   "User_Score": "7.9",
   "User_Count": 50,
   "Developer": "Nintendo",
   "Rating": "E"
 },
 {
   "Name": "Pokemon Diamond/Pokemon Pearl",
   "Platform": "DS",
   "Year_of_Release": "2006",
   "Genre": "Role-Playing",
   "Publisher": "Nintendo",
   "NA_Sales": 6.38,
   "EU_Sales": 4.46,
   "JP_Sales": 6.04,
   "Other_Sales": 1.36,
   "Global_Sales": 18.25,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Super Mario Land",
   "Platform": "GB",
   "Year_of_Release": "1989",
   "Genre": "Platform",
   "Publisher": "Nintendo",
   "NA_Sales": 10.83,
   "EU_Sales": 2.71,
   "JP_Sales": 4.18,
   "Other_Sales": 0.42,
   "Global_Sales": 18.14,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Super Mario Bros. 3",
   "Platform": "NES",
   "Year_of_Release": "1988",
   "Genre": "Platform",
   "Publisher": "Nintendo",
   "NA_Sales": 9.54,
   "EU_Sales": 3.44,
   "JP_Sales": 3.84,
   "Other_Sales": 0.46,
   "Global_Sales": 17.28,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Grand Theft Auto V",
   "Platform": "X360",
   "Year_of_Release": "2013",
   "Genre": "Action",
   "Publisher": "Take-Two Interactive",
   "NA_Sales": 9.66,
   "EU_Sales": 5.14,
   "JP_Sales": 0.06,
   "Other_Sales": 1.41,
   "Global_Sales": 16.27,
   "Critic_Score": 97,
   "Critic_Count": 58,
   "User_Score": "8.1",
   "User_Count": 3711,
   "Developer": "Rockstar North",
   "Rating": "M"
 },
 {
   "Name": "Grand Theft Auto: Vice City",
   "Platform": "PS2",
   "Year_of_Release": "2002",
   "Genre": "Action",
   "Publisher": "Take-Two Interactive",
   "NA_Sales": 8.41,
   "EU_Sales": 5.49,
   "JP_Sales": 0.47,
   "Other_Sales": 1.78,
   "Global_Sales": 16.15,
   "Critic_Score": 95,
   "Critic_Count": 62,
   "User_Score": "8.7",
   "User_Count": 730,
   "Developer": "Rockstar North",
   "Rating": "M"
 },
 {
   "Name": "Pokemon Ruby/Pokemon Sapphire",
   "Platform": "GBA",
   "Year_of_Release": "2002",
   "Genre": "Role-Playing",
   "Publisher": "Nintendo",
   "NA_Sales": 6.06,
   "EU_Sales": 3.9,
   "JP_Sales": 5.38,
   "Other_Sales": 0.5,
   "Global_Sales": 15.85,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Brain Age 2: More Training in Minutes a Day",
   "Platform": "DS",
   "Year_of_Release": "2005",
   "Genre": "Puzzle",
   "Publisher": "Nintendo",
   "NA_Sales": 3.43,
   "EU_Sales": 5.35,
   "JP_Sales": 5.32,
   "Other_Sales": 1.18,
   "Global_Sales": 15.29,
   "Critic_Score": 77,
   "Critic_Count": 37,
   "User_Score": "7.1",
   "User_Count": 19,
   "Developer": "Nintendo",
   "Rating": "E"
 },
 {
   "Name": "Pokemon Black/Pokemon White",
   "Platform": "DS",
   "Year_of_Release": "2010",
   "Genre": "Role-Playing",
   "Publisher": "Nintendo",
   "NA_Sales": 5.51,
   "EU_Sales": 3.17,
   "JP_Sales": 5.65,
   "Other_Sales": 0.8,
   "Global_Sales": 15.14,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Gran Turismo 3: A-Spec",
   "Platform": "PS2",
   "Year_of_Release": "2001",
   "Genre": "Racing",
   "Publisher": "Sony Computer Entertainment",
   "NA_Sales": 6.85,
   "EU_Sales": 5.09,
   "JP_Sales": 1.87,
   "Other_Sales": 1.16,
   "Global_Sales": 14.98,
   "Critic_Score": 95,
   "Critic_Count": 54,
   "User_Score": "8.4",
   "User_Count": 314,
   "Developer": "Polyphony Digital",
   "Rating": "E"
 },
 {
   "Name": "Call of Duty: Modern Warfare 3",
   "Platform": "X360",
   "Year_of_Release": "2011",
   "Genre": "Shooter",
   "Publisher": "Activision",
   "NA_Sales": 9.04,
   "EU_Sales": 4.24,
   "JP_Sales": 0.13,
   "Other_Sales": 1.32,
   "Global_Sales": 14.73,
   "Critic_Score": 88,
   "Critic_Count": 81,
   "User_Score": "3.4",
   "User_Count": 8713,
   "Developer": "Infinity Ward, Sledgehammer Games",
   "Rating": "M"
 },
 {
   "Name": "Pokémon Yellow: Special Pikachu Edition",
   "Platform": "GB",
   "Year_of_Release": "1998",
   "Genre": "Role-Playing",
   "Publisher": "Nintendo",
   "NA_Sales": 5.89,
   "EU_Sales": 5.04,
   "JP_Sales": 3.12,
   "Other_Sales": 0.59,
   "Global_Sales": 14.64,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Sébastien Loeb Rally Evo",
   "Platform": "XOne",
   "Year_of_Release": "2016",
   "Genre": "Racing",
   "Publisher": "Milestone S.r.l",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": 63,
   "Critic_Count": 8,
   "User_Score": "8.2",
   "User_Count": 22,
   "Developer": "Milestone S.r.l",
   "Rating": "E"
 },
 {
   "Name": "The Amazing Spider-Man 2 (2014)",
   "Platform": "PC",
   "Year_of_Release": "2014",
   "Genre": "Action",
   "Publisher": "Activision",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Style Book: Cinnamoroll",
   "Platform": "DS",
   "Year_of_Release": "2006",
   "Genre": "Misc",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "SBK Superbike World Championship",
   "Platform": "PSP",
   "Year_of_Release": "2008",
   "Genre": "Racing",
   "Publisher": "Black Bean Games",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "tbd",
   "User_Count": null,
   "Developer": "Milestone S.r.l",
   "Rating": "E10+"
 },
 {
   "Name": "The Treasures of Mystery Island 3 Pack - Save Mystery Island!",
   "Platform": "PC",
   "Year_of_Release": "2011",
   "Genre": "Puzzle",
   "Publisher": "Unknown",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Blazer Drive",
   "Platform": "DS",
   "Year_of_Release": "2008",
   "Genre": "Role-Playing",
   "Publisher": "Sega",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Deal or No Deal",
   "Platform": "PC",
   "Year_of_Release": "2006",
   "Genre": "Misc",
   "Publisher": "Focus Home Interactive",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "7.5",
   "User_Count": 8,
   "Developer": "Global Star Software",
   "Rating": "E"
 },
 {
   "Name": "Onigokko! Portable",
   "Platform": "PSP",
   "Year_of_Release": "2013",
   "Genre": "Adventure",
   "Publisher": "Alchemist",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Tour de France 2014",
   "Platform": "PS3",
   "Year_of_Release": "2014",
   "Genre": "Sports",
   "Publisher": "Focus Home Interactive",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "tbd",
   "User_Count": null,
   "Developer": "Cyanide",
   "Rating": "E"
 },
 {
   "Name": "WSC REAL 09: World Snooker Championship",
   "Platform": "PS3",
   "Year_of_Release": "2009",
   "Genre": "Sports",
   "Publisher": "Deep Silver",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Hospital Tycoon",
   "Platform": "PC",
   "Year_of_Release": "2007",
   "Genre": "Strategy",
   "Publisher": "Codemasters",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": 51,
   "Critic_Count": 8,
   "User_Score": "3.8",
   "User_Count": 29,
   "Developer": "Big Red Software",
   "Rating": "E10+"
 },
 {
   "Name": "Hoshizora no Comic Garden",
   "Platform": "DS",
   "Year_of_Release": "2008",
   "Genre": "Adventure",
   "Publisher": "D3Publisher",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Hirameki Action: Chibikko Wagyan no Daiki na Bouken",
   "Platform": "DS",
   "Year_of_Release": "2009",
   "Genre": "Action",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Rugby Challenge 3",
   "Platform": "XOne",
   "Year_of_Release": "2016",
   "Genre": "Sports",
   "Publisher": "Alternative Software",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "6.6",
   "User_Count": 5,
   "Developer": "Wicked Witch Software",
   "Rating": "E"
 },
 {
   "Name": "Eve: Burst Error R",
   "Platform": "PSV",
   "Year_of_Release": "2016",
   "Genre": "Action",
   "Publisher": "Red Flagship",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "ZombiU",
   "Platform": "XOne",
   "Year_of_Release": "2016",
   "Genre": "Action",
   "Publisher": "Ubisoft",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Time Travelers",
   "Platform": "PSP",
   "Year_of_Release": "2012",
   "Genre": "Adventure",
   "Publisher": "Level 5",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Metal Gear Solid HD Edition",
   "Platform": "X360",
   "Year_of_Release": "2011",
   "Genre": "Action",
   "Publisher": "Konami Digital Entertainment",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "tbd",
   "User_Count": null,
   "Developer": "Konami",
   "Rating": "M"
 },
 {
   "Name": "Mushi Bugyou",
   "Platform": "3DS",
   "Year_of_Release": "2013",
   "Genre": "Action",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Real Crimes: The Unicorn Killer",
   "Platform": "DS",
   "Year_of_Release": "2011",
   "Genre": "Puzzle",
   "Publisher": "Unknown",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Agatha Christie: Peril at End House",
   "Platform": "PC",
   "Year_of_Release": "2009",
   "Genre": "Adventure",
   "Publisher": "JoWood Productions",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "tbd",
   "User_Count": null,
   "Developer": "Oberon Media",
   "Rating": "T"
 },
 {
   "Name": "The Rise of the Argonauts",
   "Platform": "PC",
   "Year_of_Release": "2008",
   "Genre": "Role-Playing",
   "Publisher": "Codemasters",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Fast Racing Neo ",
   "Platform": "WiiU",
   "Year_of_Release": "2016",
   "Genre": "Action",
   "Publisher": "Nintendo",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": 81,
   "Critic_Count": 46,
   "User_Score": "8.5",
   "User_Count": 151,
   "Developer": "Shin'en",
   "Rating": "E"
 },
 {
   "Name": "Nintendogs and Cats Golden Retriever and New Friends",
   "Platform": "3DS",
   "Year_of_Release": "2011",
   "Genre": "Action",
   "Publisher": "Nintendo",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Ben 10 Omniverse 2",
   "Platform": "X360",
   "Year_of_Release": "2013",
   "Genre": "Action",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "5.1",
   "User_Count": 9,
   "Developer": "High Voltage Software",
   "Rating": "E10+"
 },
 {
   "Name": "Summer Athletics",
   "Platform": "PC",
   "Year_of_Release": "2008",
   "Genre": "Sports",
   "Publisher": "DTP Entertainment",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "tbd",
   "User_Count": null,
   "Developer": "49Games",
   "Rating": ""
 },
 {
   "Name": "Imagine Figure Skater (JP sales)",
   "Platform": "DS",
   "Year_of_Release": "2007",
   "Genre": "Sports",
   "Publisher": "Ubisoft",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Dramatical Murder Re:code",
   "Platform": "PSV",
   "Year_of_Release": "2014",
   "Genre": "Adventure",
   "Publisher": "Nitroplus",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Driving Simulator 2011",
   "Platform": "PC",
   "Year_of_Release": "2011",
   "Genre": "Racing",
   "Publisher": "N/A",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Hyakki Yagyou Kaidan Romance",
   "Platform": "PSP",
   "Year_of_Release": "2012",
   "Genre": "Action",
   "Publisher": "Quinrose",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Prison Architect",
   "Platform": "XOne",
   "Year_of_Release": "2016",
   "Genre": "Action",
   "Publisher": "Introversion Software",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": 74,
   "Critic_Count": 13,
   "User_Score": "6.7",
   "User_Count": 7,
   "Developer": "Introversion, Double Eleven",
   "Rating": ""
 },
 {
   "Name": "Bookworm Deluxe",
   "Platform": "PC",
   "Year_of_Release": "2006",
   "Genre": "Puzzle",
   "Publisher": "PopCap Games",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "8",
   "User_Count": 6,
   "Developer": "PopCap",
   "Rating": "E"
 },
 {
   "Name": "Hakuoki: Reimeiroku - Omouhase Kara",
   "Platform": "PSV",
   "Year_of_Release": "2015",
   "Genre": "Action",
   "Publisher": "Idea Factory",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "E.T. The Extra-Terrestrial",
   "Platform": "GBA",
   "Year_of_Release": "2001",
   "Genre": "Action",
   "Publisher": "NewKidCo",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": 46,
   "Critic_Count": 4,
   "User_Score": "2.4",
   "User_Count": 21,
   "Developer": "Fluid Studios",
   "Rating": "E"
 },
 {
   "Name": "Mahou Sensei Negima!? Neo-Pactio Fight!!",
   "Platform": "Wii",
   "Year_of_Release": "2007",
   "Genre": "Fighting",
   "Publisher": "Marvelous Interactive",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Sweet Honey Coming",
   "Platform": "PS2",
   "Year_of_Release": "2009",
   "Genre": "Adventure",
   "Publisher": "Kadokawa Shoten",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Psychic Detective",
   "Platform": "PS",
   "Year_of_Release": "1995",
   "Genre": "Adventure",
   "Publisher": "Electronic Arts",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Hanasaku Manimani",
   "Platform": "PSV",
   "Year_of_Release": "2014",
   "Genre": "Adventure",
   "Publisher": "5pb",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Fujiko F. Fujio Characters: Great Assembly! Slightly Fantastic Slapstick Party",
   "Platform": "3DS",
   "Year_of_Release": "2014",
   "Genre": "Action",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Super Robot Taisen: Original Generation",
   "Platform": "GBA",
   "Year_of_Release": "2002",
   "Genre": "Role-Playing",
   "Publisher": "Banpresto",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": 72,
   "Critic_Count": 13,
   "User_Score": "tbd",
   "User_Count": null,
   "Developer": "Banpresto",
   "Rating": "T"
 },
 {
   "Name": "Sugar + Spice! Anoko no Suteki na Nanimokamo",
   "Platform": "PS2",
   "Year_of_Release": "2008",
   "Genre": "Adventure",
   "Publisher": "Alchemist",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Kanokon: Esuii",
   "Platform": "PS2",
   "Year_of_Release": "2008",
   "Genre": "Adventure",
   "Publisher": "5pb",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Metal Gear Solid V: The Definitive Experience",
   "Platform": "XOne",
   "Year_of_Release": "2016",
   "Genre": "Action",
   "Publisher": "Konami Digital Entertainment",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "tbd",
   "User_Count": null,
   "Developer": "Kojima Productions",
   "Rating": "M"
 },
 {
   "Name": "Mortal Kombat: Deadly Alliance",
   "Platform": "GBA",
   "Year_of_Release": "2002",
   "Genre": "Fighting",
   "Publisher": "Midway Games",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": 81,
   "Critic_Count": 12,
   "User_Score": "8.8",
   "User_Count": 9,
   "Developer": "Criterion Games",
   "Rating": "M"
 },
 {
   "Name": "Tsukigime Ranko's Longest Day",
   "Platform": "PS3",
   "Year_of_Release": "2014",
   "Genre": "Action",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Original Frisbee Disc Sports: Ultimate & Golf",
   "Platform": "DS",
   "Year_of_Release": "2007",
   "Genre": "Action",
   "Publisher": "Destination Software, Inc",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "G1 Jockey 4 2008",
   "Platform": "PS3",
   "Year_of_Release": "2008",
   "Genre": "Sports",
   "Publisher": "Tecmo Koei",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Aikatsu Stars! My Special Appeal",
   "Platform": "3DS",
   "Year_of_Release": "2016",
   "Genre": "Action",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "End of Nations",
   "Platform": "PC",
   "Year_of_Release": "2012",
   "Genre": "Strategy",
   "Publisher": "Trion Worlds",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "Petroglyph",
   "Rating": "T"
 },
 {
   "Name": "XI Coliseum",
   "Platform": "PSP",
   "Year_of_Release": "2006",
   "Genre": "Puzzle",
   "Publisher": "Sony Computer Entertainment",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Kyoukai no Shirayuki",
   "Platform": "PSV",
   "Year_of_Release": "2016",
   "Genre": "Action",
   "Publisher": "Idea Factory",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Worms 2",
   "Platform": "PC",
   "Year_of_Release": "1997",
   "Genre": "Strategy",
   "Publisher": "Microprose",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "8.1",
   "User_Count": 12,
   "Developer": "Team 17",
   "Rating": "K-A"
 },
 {
   "Name": "Grisaia no Kajitsu: La Fruit de la Grisaia",
   "Platform": "PSP",
   "Year_of_Release": "2013",
   "Genre": "Adventure",
   "Publisher": "Prototype",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Scarlett: Nichijou no Kyoukaisen",
   "Platform": "PS2",
   "Year_of_Release": "2008",
   "Genre": "Adventure",
   "Publisher": "Kadokawa Shoten",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "7'scarlet",
   "Platform": "PSV",
   "Year_of_Release": "2016",
   "Genre": "Adventure",
   "Publisher": "Idea Factory",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Help Wanted: 50 Wacky Jobs (jp sales)",
   "Platform": "Wii",
   "Year_of_Release": "2008",
   "Genre": "Simulation",
   "Publisher": "Hudson Soft",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Yattaman Wii: BikkuriDokkiri Machine de Mou Race da Koron",
   "Platform": "Wii",
   "Year_of_Release": "2008",
   "Genre": "Racing",
   "Publisher": "Takara Tomy",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Neo Angelique Special",
   "Platform": "PSP",
   "Year_of_Release": "2008",
   "Genre": "Adventure",
   "Publisher": "Tecmo Koei",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Outdoors Unleashed: Africa 3D",
   "Platform": "3DS",
   "Year_of_Release": "2011",
   "Genre": "Sports",
   "Publisher": "Mastiff",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "tbd",
   "User_Count": null,
   "Developer": "Mastiff",
   "Rating": "T"
 },
 {
   "Name": "Real Rode",
   "Platform": "PS2",
   "Year_of_Release": "2008",
   "Genre": "Adventure",
   "Publisher": "Kadokawa Shoten",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Pony Friends 2",
   "Platform": "PC",
   "Year_of_Release": "2009",
   "Genre": "Simulation",
   "Publisher": "Eidos Interactive",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Dynasty Warriors: Eiketsuden",
   "Platform": "PS3",
   "Year_of_Release": "2016",
   "Genre": "Action",
   "Publisher": "Tecmo Koei",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Metal Gear Solid V: Ground Zeroes",
   "Platform": "PC",
   "Year_of_Release": "2014",
   "Genre": "Action",
   "Publisher": "Konami Digital Entertainment",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": 80,
   "Critic_Count": 20,
   "User_Score": "7.6",
   "User_Count": 412,
   "Developer": "Kojima Productions",
   "Rating": "M"
 },
 {
   "Name": "PGA European Tour",
   "Platform": "N64",
   "Year_of_Release": "2000",
   "Genre": "Sports",
   "Publisher": "Infogrames",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Carmageddon 64",
   "Platform": "N64",
   "Year_of_Release": "1999",
   "Genre": "Action",
   "Publisher": "Virgin Interactive",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Planet Monsters",
   "Platform": "GBA",
   "Year_of_Release": "2001",
   "Genre": "Action",
   "Publisher": "Titus",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": 67,
   "Critic_Count": 9,
   "User_Score": "tbd",
   "User_Count": null,
   "Developer": "Planet Interactive",
   "Rating": "E"
 },
 {
   "Name": "Breach",
   "Platform": "PC",
   "Year_of_Release": "2011",
   "Genre": "Shooter",
   "Publisher": "Destineer",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": 61,
   "Critic_Count": 12,
   "User_Score": "5.8",
   "User_Count": 43,
   "Developer": "Atomic Games",
   "Rating": "T"
 },
 {
   "Name": "Bust-A-Move 3000",
   "Platform": "GC",
   "Year_of_Release": "2003",
   "Genre": "Puzzle",
   "Publisher": "Ubisoft",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": 53,
   "Critic_Count": 4,
   "User_Score": "tbd",
   "User_Count": null,
   "Developer": "Taito Corporation",
   "Rating": "E"
 },
 {
   "Name": "Mega Brain Boost",
   "Platform": "DS",
   "Year_of_Release": "2008",
   "Genre": "Puzzle",
   "Publisher": "Majesco Entertainment",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": 48,
   "Critic_Count": 10,
   "User_Score": "tbd",
   "User_Count": null,
   "Developer": "Interchannel-Holon",
   "Rating": "E"
 },
 {
   "Name": "The Longest 5 Minutes",
   "Platform": "PSV",
   "Year_of_Release": "2016",
   "Genre": "Action",
   "Publisher": "Nippon Ichi Software",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Mezase!! Tsuri Master DS",
   "Platform": "DS",
   "Year_of_Release": "2009",
   "Genre": "Sports",
   "Publisher": "Hudson Soft",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Eiyuu Densetsu: Sora no Kiseki Material Collection Portable",
   "Platform": "PSP",
   "Year_of_Release": "2007",
   "Genre": "Role-Playing",
   "Publisher": "Falcom Corporation",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "STORM: Frontline Nation",
   "Platform": "PC",
   "Year_of_Release": "2011",
   "Genre": "Strategy",
   "Publisher": "Unknown",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": 60,
   "Critic_Count": 12,
   "User_Score": "7.2",
   "User_Count": 13,
   "Developer": "SimBin",
   "Rating": "E10+"
 },
 {
   "Name": "Strawberry Nauts",
   "Platform": "PSV",
   "Year_of_Release": "2016",
   "Genre": "Adventure",
   "Publisher": "Unknown",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Plushees",
   "Platform": "DS",
   "Year_of_Release": "2008",
   "Genre": "Simulation",
   "Publisher": "Destineer",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "tbd",
   "User_Count": null,
   "Developer": "Big John Games",
   "Rating": "E"
 },
 {
   "Name": "15 Days",
   "Platform": "PC",
   "Year_of_Release": "2009",
   "Genre": "Adventure",
   "Publisher": "DTP Entertainment",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": 63,
   "Critic_Count": 6,
   "User_Score": "5.8",
   "User_Count": 8,
   "Developer": "DTP Entertainment",
   "Rating": ""
 },
 {
   "Name": "Men in Black II: Alien Escape",
   "Platform": "GC",
   "Year_of_Release": "2003",
   "Genre": "Shooter",
   "Publisher": "Infogrames",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "tbd",
   "User_Count": null,
   "Developer": "Atari",
   "Rating": "T"
 },
 {
   "Name": "Aiyoku no Eustia",
   "Platform": "PSV",
   "Year_of_Release": "2014",
   "Genre": "Misc",
   "Publisher": "dramatic create",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Woody Woodpecker in Crazy Castle 5",
   "Platform": "GBA",
   "Year_of_Release": "2002",
   "Genre": "Platform",
   "Publisher": "Kemco",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "SCORE International Baja 1000: The Official Game",
   "Platform": "PS2",
   "Year_of_Release": "2008",
   "Genre": "Racing",
   "Publisher": "Activision",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Samurai Warriors: Sanada Maru",
   "Platform": "PS3",
   "Year_of_Release": "2016",
   "Genre": "Action",
   "Publisher": "Tecmo Koei",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "LMA Manager 2007",
   "Platform": "X360",
   "Year_of_Release": "2006",
   "Genre": "Sports",
   "Publisher": "Codemasters",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Haitaka no Psychedelica",
   "Platform": "PSV",
   "Year_of_Release": "2016",
   "Genre": "Adventure",
   "Publisher": "Idea Factory",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Spirits & Spells",
   "Platform": "GBA",
   "Year_of_Release": "2003",
   "Genre": "Platform",
   "Publisher": "Wanadoo",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 },
 {
   "Name": "Winning Post 8 2016",
   "Platform": "PSV",
   "Year_of_Release": "2016",
   "Genre": "Simulation",
   "Publisher": "Tecmo Koei",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": null,
   "Critic_Count": null,
   "User_Score": "",
   "User_Count": null,
   "Developer": "",
   "Rating": ""
 }
]

export default data