export { default as TopGamesByDate } from './TopGamesByDate/TopGamesByDate'
export { default as TopGamesInPlatform } from './TopGamesInPlatform/TopGamesInPlatform'
export { default as MainNav } from './MainNav/MainNav'
export { default as GameHero } from './GameHero/GameHero'
export { default as GameDetailsCard } from './GameDetailsCard/GameDetailsCard'
export { default as GamePhotos } from './GamePhotos/GamePhotos'